import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Teams from '../components/Teams'

const Home: NextPage = () => {
  return (
    <div className='py-4 px-4'>
      <Head>
        <title>KulloLabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Teams/>
      <Footer/>
    </div>
  )
}

export default Home
